version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: broccoli-funnel
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: html-entities
    versions:
    - 2.1.0
    - 2.1.1
    - 2.3.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
  - dependency-name: "@glimmer/component"
    versions:
    - 1.0.3
  - dependency-name: "@glimmer/application"
    versions:
    - 1.0.3
  - dependency-name: "@glimmer/ssr"
    versions:
    - 1.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: "@glimmer/blueprint"
    versions:
    - 1.0.3
