#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --url-ignore https://t.co/6yhjmjQrYD,http://localhost:4000/my_page --only-4xx --url-swap simplabs.com:localhost\:4000
