on:
  schedule:
    # Every Sunday 23:00
    - cron: '0 23 * * 0'
  pull_request:
    types: [labeled, unlabeled]
  issue_comment:
    types: [edited]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TWIOS_BRANCH: ${{ github.event.pull_request.head.ref || 'master' }}
  TWIOS_PR_REF: ${{ github.event.pull_request.head.ref }}

permissions:
  pull-requests: write

jobs:
  create_twios:
    runs-on: ubuntu-latest
    if: ${{!github.event.pull_request.body && github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'twios'}}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch $TWIOS_BRANCH
        run: |
          git fetch origin $TWIOS_BRANCH
          git checkout $TWIOS_BRANCH
      - name: Configure local git
        run: |
          git config --global user.email "twios@twios_test_dev.com"
          git config --global user.name "TWIOS Dev"
      - name: Generate Comment
        run: |
          GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN ./twios/this-week.sh comment > comment.txt
      - name: Generate TWIOS
        run: GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN ./twios/this-week.sh
      - name: Push new TWIOS
        run: |
          FORMATTED_DATE="$(date +"%Y-%m-%d")"
          BRANCH_NAME="twios-$FORMATTED_DATE"
          git checkout -b $BRANCH_NAME
          git add **/*.md **/*.json && git commit -m "$BRANCH_NAME"
          git push --set-upstream origin $BRANCH_NAME
          gh pr create --base main --head $BRANCH_NAME --title "TWIOS $FORMATTED_DATE" --body-file comment.txt

  edit_twios:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.body && contains(github.event.pull_request.head.ref, 'twios')}}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch $TWIOS_PR_REF
        run: |
          git fetch origin $TWIOS_PR_REF
          git checkout $TWIOS_PR_REF
      - name: Configure local git
        run: |
          git config --global user.email "twios@twios_test_dev.com"
          git config --global user.name "TWIOS Dev"
      - name: Read PR comment body
        run: |
          GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN ./twios/this-week.sh comment --comment="${{ github.event.pull_request.body }}"
      - name: Generate TWIOS
        run: GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN ./twios/this-week.sh -edit
      - name: Push updated TWIOS
        run: |
          git add **/*.md **/*.json && git commit -m "Edited $TWIOS_PR_REF"
          git push
